-- MySQL Script generated by MySQL Workbench
-- Tue Dec 27 19:44:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HotelManagmentSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HotelManagmentSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelManagmentSystem` DEFAULT CHARACTER SET utf8 ;
USE `HotelManagmentSystem` ;

-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Spol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Spol` (
  `id_spola` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_spola`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Soba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Soba` (
  `id_sobe` INT NOT NULL AUTO_INCREMENT,
  `kat` INT NOT NULL,
  `broj_sobe` INT NOT NULL,
  `kapacitet` INT NOT NULL,
  `opis` VARCHAR(100) NULL,
  PRIMARY KEY (`id_sobe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Pacijent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Pacijent` (
  `id_pacijenta` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NOT NULL,
  `prezime` VARCHAR(50) NOT NULL,
  `datum_rodjenja` DATE NOT NULL,
  `adresa` VARCHAR(100) NOT NULL,
  `kontakt_broj` VARCHAR(50) NOT NULL,
  `kontakt_mail` VARCHAR(50) NOT NULL,
  `Soba_id_sobe` INT NOT NULL,
  `Spol_id_spola` INT NOT NULL,
  PRIMARY KEY (`id_pacijenta`),
  INDEX `fk_Pacijent_Soba1_idx` (`Soba_id_sobe` ASC) VISIBLE,
  INDEX `fk_Pacijent_Spol1_idx` (`Spol_id_spola` ASC) VISIBLE,
  CONSTRAINT `fk_Pacijent_Soba`
    FOREIGN KEY (`Soba_id_sobe`)
    REFERENCES `HotelManagmentSystem`.`Soba` (`id_sobe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacijent_Spol`
    FOREIGN KEY (`Spol_id_spola`)
    REFERENCES `HotelManagmentSystem`.`Spol` (`id_spola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Pozicija_ms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Pozicija_ms` (
  `id_pozicije_ms` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pozicije_ms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Specijalizacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Specijalizacija` (
  `id_specijalizacije` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_specijalizacije`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Smjena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Smjena` (
  `id_smjene` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  `pocetak_smjene` TIME NOT NULL,
  `kraj_smjene` TIME NOT NULL,
  `pocetak_pauze` TIME NOT NULL,
  `kraj_pauze` TIME NOT NULL,
  PRIMARY KEY (`id_smjene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Medicinska_sestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Medicinska_sestra` (
  `id_mecinske_sestre` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NOT NULL,
  `prezime` VARCHAR(50) NOT NULL,
  `placa` DOUBLE NOT NULL,
  `Pozicija_ms_id_pozicije_ms` INT NOT NULL,
  `Specijalizacija_id_specijalizacije` INT NOT NULL,
  `Smjena_id_smjene` INT NOT NULL,
  PRIMARY KEY (`id_mecinske_sestre`),
  INDEX `fk_Medicinska_sestra_Pozicija_ms1_idx` (`Pozicija_ms_id_pozicije_ms` ASC) VISIBLE,
  INDEX `fk_Medicinska_sestra_Specijalizacija1_idx` (`Specijalizacija_id_specijalizacije` ASC) VISIBLE,
  INDEX `fk_Medicinska_sestra_Smjena1_idx` (`Smjena_id_smjene` ASC) VISIBLE,
  CONSTRAINT `fk_Medicinska_sestra_Pozicija_ms`
    FOREIGN KEY (`Pozicija_ms_id_pozicije_ms`)
    REFERENCES `HotelManagmentSystem`.`Pozicija_ms` (`id_pozicije_ms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicinska_sestra_Specijalizacija`
    FOREIGN KEY (`Specijalizacija_id_specijalizacije`)
    REFERENCES `HotelManagmentSystem`.`Specijalizacija` (`id_specijalizacije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicinska_sestra_Smjena`
    FOREIGN KEY (`Smjena_id_smjene`)
    REFERENCES `HotelManagmentSystem`.`Smjena` (`id_smjene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Medicinska_sestra_has_Soba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Medicinska_sestra_has_Soba` (
  `Medicinska_sestra_id_mecinske_sestre` INT NOT NULL,
  `Soba_id_sobe` INT NOT NULL,
  PRIMARY KEY (`Medicinska_sestra_id_mecinske_sestre`, `Soba_id_sobe`),
  INDEX `fk_Medicinska_sestra_has_Soba_Soba1_idx` (`Soba_id_sobe` ASC) VISIBLE,
  INDEX `fk_Medicinska_sestra_has_Soba_Medicinska_sestra1_idx` (`Medicinska_sestra_id_mecinske_sestre` ASC) VISIBLE,
  CONSTRAINT `fk_Medicinska_sestra_has_Soba_Medicinska_sestra`
    FOREIGN KEY (`Medicinska_sestra_id_mecinske_sestre`)
    REFERENCES `HotelManagmentSystem`.`Medicinska_sestra` (`id_mecinske_sestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicinska_sestra_has_Soba_Soba`
    FOREIGN KEY (`Soba_id_sobe`)
    REFERENCES `HotelManagmentSystem`.`Soba` (`id_sobe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Dijagnoza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Dijagnoza` (
  `id_dijagnoze` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  `opis` VARCHAR(100) NULL,
  PRIMARY KEY (`id_dijagnoze`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Lijecnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Lijecnik` (
  `id_lijecnika` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NOT NULL,
  `prezime` VARCHAR(50) NOT NULL,
  `kontakt_broj` VARCHAR(50) NOT NULL,
  `kontakt_mail` VARCHAR(50) NULL,
  `Smjena_id_smjene` INT NOT NULL,
  `Specijalizacija_id_specijalizacije` INT NOT NULL,
  `Dijagnoza_id_dijagnoze` INT NOT NULL,
  PRIMARY KEY (`id_lijecnika`),
  INDEX `fk_Lijecnik_Smjena1_idx` (`Smjena_id_smjene` ASC) VISIBLE,
  INDEX `fk_Lijecnik_Specijalizacija1_idx` (`Specijalizacija_id_specijalizacije` ASC) VISIBLE,
  INDEX `fk_Lijecnik_Dijagnoza1_idx` (`Dijagnoza_id_dijagnoze` ASC) VISIBLE,
  CONSTRAINT `fk_Lijecnik_Smjena`
    FOREIGN KEY (`Smjena_id_smjene`)
    REFERENCES `HotelManagmentSystem`.`Smjena` (`id_smjene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lijecnik_Specijalizacija`
    FOREIGN KEY (`Specijalizacija_id_specijalizacije`)
    REFERENCES `HotelManagmentSystem`.`Specijalizacija` (`id_specijalizacije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lijecnik_Dijagnoza`
    FOREIGN KEY (`Dijagnoza_id_dijagnoze`)
    REFERENCES `HotelManagmentSystem`.`Dijagnoza` (`id_dijagnoze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Lijek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Lijek` (
  `id_lijeka` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  `napomena` VARCHAR(200) NULL,
  PRIMARY KEY (`id_lijeka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Status_pregleda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Status_pregleda` (
  `id_statusa_pregleda` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_statusa_pregleda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Simptom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Simptom` (
  `id_simptoma` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  `opis` VARCHAR(100) NULL,
  PRIMARY KEY (`id_simptoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Pregled`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Pregled` (
  `id_pregleda` INT NOT NULL AUTO_INCREMENT,
  `datum_termina_pregleda` DATE NOT NULL,
  `vrijeme_termina_pregleda` TIME NOT NULL,
  `Status_pregleda_id_statusa_pregleda` INT NOT NULL,
  `Dijagnoza_id_dijagnoze` INT NOT NULL,
  PRIMARY KEY (`id_pregleda`),
  INDEX `fk_Pregled_Status_pregleda1_idx` (`Status_pregleda_id_statusa_pregleda` ASC) VISIBLE,
  INDEX `fk_Pregled_Dijagnoza1_idx` (`Dijagnoza_id_dijagnoze` ASC) VISIBLE,
  CONSTRAINT `fk_Pregled_Status_pregleda`
    FOREIGN KEY (`Status_pregleda_id_statusa_pregleda`)
    REFERENCES `HotelManagmentSystem`.`Status_pregleda` (`id_statusa_pregleda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregled_Dijagnoza`
    FOREIGN KEY (`Dijagnoza_id_dijagnoze`)
    REFERENCES `HotelManagmentSystem`.`Dijagnoza` (`id_dijagnoze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Pacijent_has_Pregled`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Pacijent_has_Pregled` (
  `Pacijent_id_pacijenta` INT NOT NULL,
  `Pregled_id_pregleda` INT NOT NULL,
  PRIMARY KEY (`Pacijent_id_pacijenta`, `Pregled_id_pregleda`),
  INDEX `fk_Pacijent_has_Pregled_Pregled1_idx` (`Pregled_id_pregleda` ASC) VISIBLE,
  INDEX `fk_Pacijent_has_Pregled_Pacijent1_idx` (`Pacijent_id_pacijenta` ASC) VISIBLE,
  CONSTRAINT `fk_Pacijent_has_Pregled_Pacijent`
    FOREIGN KEY (`Pacijent_id_pacijenta`)
    REFERENCES `HotelManagmentSystem`.`Pacijent` (`id_pacijenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacijent_has_Pregled_Pregled`
    FOREIGN KEY (`Pregled_id_pregleda`)
    REFERENCES `HotelManagmentSystem`.`Pregled` (`id_pregleda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Lijek_has_Dijagnoza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Lijek_has_Dijagnoza` (
  `Lijek_id_lijeka` INT NOT NULL,
  `Dijagnoza_id_dijagnoze` INT NOT NULL,
  PRIMARY KEY (`Lijek_id_lijeka`, `Dijagnoza_id_dijagnoze`),
  INDEX `fk_Lijek_has_Dijagnoza_Dijagnoza1_idx` (`Dijagnoza_id_dijagnoze` ASC) VISIBLE,
  INDEX `fk_Lijek_has_Dijagnoza_Lijek1_idx` (`Lijek_id_lijeka` ASC) VISIBLE,
  CONSTRAINT `fk_Lijek_has_Dijagnoza_Lijek`
    FOREIGN KEY (`Lijek_id_lijeka`)
    REFERENCES `HotelManagmentSystem`.`Lijek` (`id_lijeka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lijek_has_Dijagnoza_Dijagnoza`
    FOREIGN KEY (`Dijagnoza_id_dijagnoze`)
    REFERENCES `HotelManagmentSystem`.`Dijagnoza` (`id_dijagnoze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelManagmentSystem`.`Simptom_has_Pregled`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelManagmentSystem`.`Simptom_has_Pregled` (
  `Simptom_id_simptoma` INT NOT NULL,
  `Pregled_id_pregleda` INT NOT NULL,
  PRIMARY KEY (`Simptom_id_simptoma`, `Pregled_id_pregleda`),
  INDEX `fk_Simptom_has_Pregled_Pregled1_idx` (`Pregled_id_pregleda` ASC) VISIBLE,
  INDEX `fk_Simptom_has_Pregled_Simptom1_idx` (`Simptom_id_simptoma` ASC) VISIBLE,
  CONSTRAINT `fk_Simptom_has_Pregled_Simptom`
    FOREIGN KEY (`Simptom_id_simptoma`)
    REFERENCES `HotelManagmentSystem`.`Simptom` (`id_simptoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Simptom_has_Pregled_Pregled`
    FOREIGN KEY (`Pregled_id_pregleda`)
    REFERENCES `HotelManagmentSystem`.`Pregled` (`id_pregleda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
